.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/ktlint.xml, .idea/inspectionProfiles/profiles_settings.xml, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurationType.kt
in support of #16 
see https://github.com/shyiko/ktlint#-with-intellij-idea
Sets up built in formatter to match ktlint according to Android Kotlin Style Guide via:
`ktlint --apply-to-idea-project --android`
next PR will set up the linter and integrate it into the build
=> Align intellij built in formatter with ktlint

.idea/codeStyles/Project.xml, .idea/compiler.xml, build.gradle.kts, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldUiResources.kt
fixes #16 
Spotless plugin (used in cloud tools for intellij also) has built in support for ktlint.
There are a few peculiarities that we can iron out as we go along:
- the IJ formatter doesn't seem to enforce the line length rule (even though the linter will fail since 100 char limit is part of the Android Studio style guide)
- The current settings can lead to some strange formatting (see the changes to `SkaffoldUiResources` in this PR). As far as I can tell this is correct Kotlin styling 
- ktlint has some basic auto-formatting limitations: it cannot (yet?) auto-format indentation problems, convert wildcard imports etc.. The IntelliJ formatter / import optimizer can fix these though.
=> Add ktlint Kotlin linter via Spotless plugin

build.gradle.kts, common-test-lib/build.gradle.kts, common-test-lib/src/main/kotlin/com/google/container/tools/test/ContainerToolsRule.kt, common-test-lib/src/test/kotlin/com/google/container/tools/test/ContainerToolsRule.kt, skaffold/build.gradle.kts, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldFiles.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldFilesTest.kt
Works towards #37, and #19.
Initializes unit tests rule for using IDE project and module basic test fixture, similar to [CloudToolsRule](https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/common-test-lib/src/main/java/com/google/cloud/tools/intellij/testing/CloudToolsRule.java).
For the start, test fixtures are always "light", i.e. giving minimal IDE infrastructure with slimmed down project and module support which should speed up the tests and be enough for majority of the unit tests.
Unit test names follow the convention most Kotlin tests follow.
Next PR will also add unit tests for project-based YAML search once I figure out proper way to add files to the mock project.
=> Sets up initial test module structure, container test rule and initial Skaffold file tests.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldFiles.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldFilesTest.kt
Addition for #37.
Tests Skaffold files not named `skaffold.yaml` and search in the empty project.
=> Expanded coverage on Skaffold files search.

.idea/dictionaries/ivanporty.xml, build.gradle.kts, common-test-lib/build.gradle.kts, common-test-lib/src/main/kotlin/com/google/container/tools/test/ContainerToolsRule.kt, common-test-lib/src/main/kotlin/com/google/container/tools/test/TestService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldFileService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldFiles.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/BaseSkaffoldSettingsEditor.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldFilesComboBox.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldFileServiceTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldFilesTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/SkaffoldFilesComboBoxTest.kt, skaffold/src/test/resources/plugin.xml
Part of #19.
Work towards #12, #13.
In order to thouroughly test `SkaffoldComboBox` class and mock Skaffold files search across the project, Skaffold file search is now made an IDE service. 
To support testing/mocking it with combo box and for later unit tests, test service support (with annotation, similar to Cloud Tools approach) is added, along with support for Mockk mocking library, which seems to be the most popular choice for Kotlin unit tests as of now.
=> Created initial support for Mockk, IJ test services, Skaffold files as a service to test SkaffoldComboBox.

common-test-lib/src/main/kotlin/com/google/container/tools/test/ContainerToolsRule.kt, common-test-lib/src/main/kotlin/com/google/container/tools/test/TestService.kt, common-test-lib/src/main/kotlin/com/google/container/tools/test/TestUtils.kt, common-test-lib/src/main/kotlin/com/google/container/tools/test/UiTest.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/BaseSkaffoldSettingsEditor.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurations.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/BaseSkaffoldSettingsEditorTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/SkaffoldFilesComboBoxTest.kt
Work towards #12, #13.
Part of #19.
Adds base run configuration (`BaseSkaffoldRunConfiguration`) which includes persisted attribute to store saved Skaffold configuration file between restarts and changes.
Includes test for base settings editor that uses this configuration settings.
For unit tests, introduces `@UiTest` annotation to allow individual tests to run on UI thread, if they manipulate or access UI components or related state to avoid possible unit test flakiness.
=>  Creates base config for both Skaffold run types to persist common Skaffold settings.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldExecutorService.kt, skaffold/src/main/resources/META-INF/skaffold.xml, skaffold/src/test/kotlin/com/google/container/tools/skaffold/DefaultSkaffoldExecutorServiceTest.kt
Progress towards #12, #13.
Creates a service that constructs Skaffold command line and launches system process based on the resulting command line. Service is defined with an interface. Default implementation assumes Skaffold is already installed and present in PATH on the system (current behavior for command line users.)
Next PR will use this service to start processes based on run configurations.
The service interface is also going to be used when Skaffold managed installation implementation is complete and will be used to execute Skaffold using managed binary.
=>  Adds Skaffold executor service to build Skaffold commands and execute process.

build.gradle.kts, src/main/resources/META-INF/plugin.xml
IntelliJ Gradle plugin was enforcing minimum version of the IDE used to build it (2018.2+) to run the plugin if `updateSinceUntilBuild` property is not set to `false`.
=> Expand version range to include upcoming 2018.3 IDE, allow older IDEs to use the plugin.

.idea/runConfigurations/Google_Container_Tools.xml
Currently it runs `runIde` sequentially for all sub-projects.
=> Made sure IntelliJ run target runs IDE only once for root plugin.

src/main/resources/META-INF/plugin.xml
While testing non-Java IDEs it turns out the run configurations are not loaded if plugin does not declare `lang` module dependency (same as previous Cloud Tools plugin). Adding the dependency enables the run configurations.
=> Added lang module dependency to enable run configurations in non-Java IDEs.

src/main/resources/META-INF/plugin.xml
Fixes #61. Makes sure the plugin only starts in IDEs no earlier than 2018.2 which has the latest UI features bundled.
=> Reduce range of supported IDEs to ensure compatibility.

core/build.gradle.kts, core/src/main/kotlin/com/google/container/tools/PluginInfo.kt, core/src/main/kotlin/com/google/container/tools/core/PluginInfo.kt, core/src/main/resources/META-INF/core.xml, settings.gradle, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldExecutorService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldLabels.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt, skaffold/src/main/resources/messages/SkaffoldBundle.properties, skaffold/src/test/kotlin/com/google/container/tools/skaffold/DefaultSkaffoldExecutorServiceTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldLabelsTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineStateTest.kt, skaffold/src/test/resources/plugin.xml, src/main/resources/META-INF/plugin.xml
Fixes #68.
When GKE cluster is used for deployment with Skaffold, labels will identify Container Tools IntelliJ plugin is used for Skaffold pipeline with additional details, such as IDE type and version.
Added `core` module for core utilities and functionality that most probably could be shared between the modules. For now it includes plugin version information there.
Labels are simple key-value pairs according to K8s specification, and passed on to Skaffold using `--label` flag.
Resulting deployment with label list, on GKE screenshot:
=>  Provides custom plugin labels for all Skaffold deployments for server-side metrics.

gradle.properties, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetector.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldFilesComboBox.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurations.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineStateTest.kt
Fixes #80.
A number of incompatible changes have been made in 2018.3, in particular with nullability of actions, generics for RunConfigBase and deprecation of project base directory property. This all has been addressed for plugin to compile and work on 2018.3
=> Update APIs and fix deprecations for 2018.3 support.

build.gradle.kts, common-test-lib/build.gradle.kts
Follow up for #80.
2018.3 is Kotlin 1.3, safe to use for our code, no obsolete or deprecated features used, and use Gradle exclude to make sure kotlin plugin version takes precedence over `mockk` dependencies.
=> Upgrade to Kotlin 1.3 to be in line with 2018.3

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldExecutorService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/BaseSkaffoldSettingsEditor.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldDevSettingsEditor.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurations.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldSingleRunSettingsEditor.kt, skaffold/src/main/resources/messages/SkaffoldBundle.properties, skaffold/src/test/kotlin/com/google/container/tools/skaffold/DefaultSkaffoldExecutorServiceTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/BaseSkaffoldSettingsEditorTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/SkaffoldSingleRunSettingsEditorTest.kt
Fixes #69.
Adds UI option to enable log tailing for single (deployment) mode:
Once deployment (successfully) completes, logs are streamed until process is killed. Deployment itself stays working:
=> Adds tail logs support for single deployment mode

src/main/kotlin/com/google/container/tools/diagnostics/GoogleFeedbackErrorReporter.kt
bug fix. lastActionId is nullable so need to use a nullable type with a check to prevent an NPE.
=> Nullable type for lastActionId in error reporting

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetector.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurationType.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetectorTest.kt
#7 enabled automatic addition of Skaffold configurations but used new API not available on 2018.2 family of IDEs. There is a more standard way to create configurations using factory IDs and configuration type which is used now and this enabled automatic configurations on 2018.2 as well as 2018.3.
=> Refactor API usage for automatically adding run configurations in 2018.2

src/main/resources/META-INF/plugin.xml
I'm testing out the release process end-to-end and this field is required for publishing. 
Adding a placeholder for now. Will be updated once we put in place our initial documentation.
=> Add placeholder plugin.xml plugin description field

kokoro/unix/release.sh
There was an error in the bash script that I found doing an end-to-end release. The file path was not correctly being extracted into a variable. This fixes it (tested).
=> Fix release script env var file cat

skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditorTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/SkaffoldFilesComboBoxTest.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/SkaffoldSingleRunSettingsEditorTest.kt
Follow up for #95.
UI code for run configurations has been moved to `run.ui` package, moves remaining test code for corresponding classes there as well.
=> Organize test code for run.ui package.

skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditorTest.kt
Missing test to cover proper restoration of Skaffold file selection when `resetFrom()` existing settings.
=> Added test case for Skaffold file selection in base settings editor.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldFileService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldFileServiceTest.kt
Fixes #96.
Instead of non-YAML regex, use YAML parser based detection for easier detection of valid Skaffold YAML files.
=> Use parsed YAML structure to better detect valid Skaffold files.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldYamlConfiguration.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditor.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/ui/SkaffoldFilesComboBox.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/ui/SkaffoldProfilesComboBox.kt
Fixes #114, different approach to fix #100.
Instead of saving files which is not allowed (along with file syncs and any other cache/edit save operations) from the modal dialogs, use PSI file content that contains the latest up-to-date memory representation of the file and the latest edits.
=> Fix write block by using PSI data when available for proper sync

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetector.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/metrics/SkaffoldTracking.kt
Work towards #110.
Adds client ping when a user decides to auto-create Skaffold configurations (both deploy and develop in our case) from the notification, after Skaffold configuration has been detected.
=> Client side metrics for auto created Skaffold configurations.

core/src/main/kotlin/com/google/container/tools/core/settings/UsageTrackerConfigurableProvider.kt, core/src/main/resources/META-INF/core.xml
fixes https://github.com/GoogleContainerTools/google-container-tools-intellij/pull/119#issuecomment-452387513
Will prevent multiple instances of the tracking panel from showing up when users are using old versions of the GCT plugin (where the panel does not have an ID configured and therefore the platform can't handle de-duplication for us).
More explanation is in the comments on the code.
=> Fix for shared panel bug for users of old GCT plugin

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationRunManagerListener.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/metrics/SkaffoldTracking.kt, skaffold/src/main/resources/META-INF/skaffold.xml
Fixes #110. (the last item in this issue is hard to figure out yet and I'll file a separate issue for it out of the current milestone.)
Uses project component, project message bus and Run Manager events to catch new configurations being added for Skaffold and send appropriate client tracking events.
=> Send metrics on Skaffold add configurations using project events and message bus.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetector.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/SkaffoldConfigurationDetectorTest.kt
Fixes #94.
Uses VFS manager and listener to track YAML file content and prompt to create Skaffold configs when new valid Skaffold YAML is created. This should complete automatic Skaffold presence detection in addition to file detection when a new project is opened. 
Immediately shows prompt to create Skaffold configurations if any YAML file in the project becomes valid Skaffold file and no Skaffold configurations exists.
=> Shows prompt to create Skaffold configurations if any YAML file in the project becomes valid Skaffold file

src/main/resources/META-INF/plugin.xml
This ID can be surfaced to the user. One example is when using `externalDependencies.xml` file declaring this plugin as a dependency; in this case the IDE will show a notification showing this ID suggesting to install the plugin.
=> Change plugin id to more readable format

skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldRunConfigurations.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditor.kt, skaffold/src/main/resources/messages/SkaffoldBundle.properties, skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditorTest.kt
Work towards #52.
See #52 and GoogleContainerTools/skaffold#1057 for more details.
This PR sets up UI and settings along with unit tests for image repository override support.
The UI:
=> UI and settings for image repository override.

skaffold/src/test/kotlin/com/google/container/tools/skaffold/run/ui/BaseSkaffoldSettingsEditorTest.kt
Missed unit test to make sure empty field value converted to null and then use null to check default image repo is not set.
=> Added unit test for empty default image repo field.

skaffold/src/main/kotlin/com/google/container/tools/skaffold/SkaffoldExecutorService.kt, skaffold/src/main/kotlin/com/google/container/tools/skaffold/run/SkaffoldCommandLineState.kt, skaffold/src/test/kotlin/com/google/container/tools/skaffold/DefaultSkaffoldExecutorServiceTest.kt
Fixes #52.
Adds support to pass default image repository name to Skaffold CLI and override manifest defined image repository.
Sample configuration:
Resulting CLI and substituted repository with the original image name (Skaffold functionality)
:
=> Added CLI support and tests for default image repo option.

examples/hello-spring-boot/k8s/web.yaml, examples/hello-spring-boot/skaffold.yaml
It should make it possible to run this for all team members without additional setup and makes the image name cleaner and matching the project name too.
=> Use team owned GCR repository and matching image name.
